CREATE OR REPLACE PROCEDURE "AD_STP_TGFPROCAB_IMP" (
    P_CODUSU NUMBER,
    P_IDSESSAO VARCHAR2,
    P_QTDLINHAS NUMBER,
    P_MENSAGEM OUT VARCHAR2
) AS
    PARAM_CODPROD NUMBER;
    V_NUNICO INT;
    V_CODPROD INT;
BEGIN
    PARAM_CODPROD := ACT_INT_PARAM(P_IDSESSAO, 'CODPROD');

    SELECT COUNT(1)
    INTO V_CODPROD
    FROM AD_TGFPROCAB
    WHERE CODPROD = PARAM_CODPROD;

    SELECT NVL(MAX(NUNICO),0)+1
    INTO V_NUNICO
    FROM AD_TGFPROCAB;

    IF V_CODPROD >= 1 THEN
        raise_application_error(-20101,
            fc_formatahtml(
                p_mensagem => 'Importação não realizada.',
                p_motivo   => 'O produto de código '||PARAM_CODPROD||' já existe na base de dados.',
                p_solucao  => 'O Produto não pode ser importado novamente. Localizar pelo código e prosseguir com a atualização'
            )
        );
    END IF;

    INSERT INTO AD_TGFPROCAB (
        AD_CODEND, AD_DESCRICAOCOMEX, AD_IMPRIMEETIQUETA, AD_KITFANTASMA,
        AD_OBSNF, AD_QTDMINVENDA, AD_SEPARAPROD, APROVAFIS, CARACTERISTICAS,
        CODGRUPOPROD, CODLOCALPADRAO, CODPROD, CODUSU, CODUSUALTER,
        CODUSUINCLUSAO, CODVOL, DESCRPROD, DHALTERACAO, DHAPROVACAO,
        DHINCLUSAO, FABRICANTE, NUNICO, ORIGPROD, PRODUTONFE, REFERENCIA,
        REPROCESSAR, SOLCOMPRA, TEMRASTROLOTE, TIPCONTEST, TIPLANCNOTA,
        USALOCAL, USALOTEDTFAB, USALOTEDTVAL, USOPROD, VENCOMPINDIV
    )
    (SELECT 
        AD_CODEND, AD_DESCRICAOCOMEX, AD_IMPRIMEETIQUETA, AD_KITFANTASMA,
        AD_OBSNF, AD_QTDMINVENDA, AD_SEPARAPROD, 1, CARACTERISTICAS,
        CODGRUPOPROD, CODLOCALPADRAO, CODPROD, STP_GET_CODUSULOGADO,
        STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, CODVOL, DESCRPROD,
        SYSDATE, SYSDATE, SYSDATE, FABRICANTE, V_NUNICO, ORIGPROD,
        PRODUTONFE, REFERENCIA, 'N', SOLCOMPRA, TEMRASTROLOTE, TIPCONTEST,
        TIPLANCNOTA, USALOCAL, USALOTEDTFAB, USALOTEDTVAL, USOPROD, VENCOMPINDIV 
     FROM TGFPRO 
     WHERE CODPROD = PARAM_CODPROD
    );

    COMMIT;

    INSERT INTO AD_TGFPROFIS (
        AD_GRAMAMLPMPF, AD_PMPF, CLASSUBTRIB, CODCTACTB, CODESPECST, CODEXNCM,
        CODIPI, CODUSU, CODUSUALTER, CSTIPIENT, CSTIPISAI, DHALTERACAO,
        DHAPROVACAO, GRUPOCOFINS, GRUPOCSSL, GRUPOICMS, GRUPOICMS2, GRUPOPIS,
        IDENTIMOB, NCM, NUNICO, REPROCESSAR, SEQ, TEMICMS, TEMIPICOMPRA,
        TEMIPIVENDA, TIPSUBST, UTILIMOB
    )
    (SELECT 
        AD_GRAMAMLPMPF, AD_PMPF, CLASSUBTRIB, CODCTACTB, CODESPECST, CODEXNCM,
        CODIPI, STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, CSTIPIENT, CSTIPISAI,
        SYSDATE, SYSDATE, GRUPOCOFINS, GRUPOCSSL, GRUPOICMS, GRUPOICMS2, GRUPOPIS,
        IDENTIMOB, NCM, V_NUNICO, 'N', 1, TEMICMS, TEMIPICOMPRA, TEMIPIVENDA,
        TIPSUBST, UTILIMOB 
     FROM TGFPRO 
     WHERE CODPROD = PARAM_CODPROD
    );

    INSERT INTO AD_TGFPROGER (
        AD_PALLET, AD_PESAGEM, AD_SEPARACAO, AD_VOLUMETRIA, ALTURA, CODUSU,
        CODUSUALTER, DECQTD, DECVLR, DHALTERACAO, DHAPROVACAO, ESPESSURA, ESTMIN,
        LARGURA, LEADTIME, M3, NUNICO, PERMCOMPPROD, PESOBRUTO, PESOLIQ,
        PRAZOVAL, QTDEMB, RASTRESTOQUE, REPROCESSAR, SEQ
    )
    (SELECT 
        AD_PALLET, AD_PESAGEM, AD_SEPARACAO, AD_VOLUMETRIA, ALTURA,
        STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, DECQTD, DECVLR, SYSDATE,
        SYSDATE, ESPESSURA, ESTMIN, LARGURA, LEADTIME, M3, V_NUNICO,
        PERMCOMPPROD, PESOBRUTO, PESOLIQ, PRAZOVAL, QTDEMB, RASTRESTOQUE, 'N', 1 
     FROM TGFPRO 
     WHERE CODPROD = PARAM_CODPROD
    );

    INSERT INTO AD_TGFPROIMP (
        CALCDIFAL, CODEMP, CODENQIPIENT, CODENQIPISAI, CODESPECST, CODUSU,
        CODUSUALTER, CSTIPIENT, CSTIPISAI, DHALTERACAO, DHAPROVACAO,
        GRUPOICMS, GRUPOICMS2, NUNICO, ORIGPROD, PERCCMTEST, PERCCMTFED,
        PERCCMTIMP, PERCCMTNAC, REPROCESSAR, SEQ, TEMICMS, TEMIPICOMPRA,
        TEMIPIVENDA, TIPOITEMSPED, TIPSUBST, USOPROD
    )
    (SELECT 
        CALCDIFAL, CODEMP, CODENQIPIENT, CODENQIPISAI, CODESPECST,
        STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, CSTIPIENT, CSTIPISAI,
        SYSDATE, SYSDATE, GRUPOICMS, GRUPOICMS2, V_NUNICO, ORIGPROD,
        PERCCMTEST, PERCCMTFED, PERCCMTIMP, PERCCMTNAC, 'N', ROWNUM SEQ,
        TEMICMS, TEMIPICOMPRA, TEMIPIVENDA, TIPOITEMSPED, TIPSUBST, USOPROD 
     FROM TGFPEM 
     WHERE CODPROD = PARAM_CODPROD
    );

    INSERT INTO AD_TGFPROPAS (
        CODUSU, CODUSUALTER, DESCR, DHALTERACAO, DHAPROVACAO, NUNICO,
        REPROCESSAR, RPM, SEQ
    )
    (SELECT 
        STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, DESCR, SYSDATE,
        SYSDATE, V_NUNICO, 'N', RPM, SEQ 
     FROM AD_PASSOAP 
     WHERE CODPROD = PARAM_CODPROD
    );

    INSERT INTO AD_TGFPROUNI (
        CODBARRA, CODUSU, CODUSUALTER, CODVOL, DHALTERACAO, DHAPROVACAO,
        DIVIDEMULTIPLICA, NUNICO, QUANTIDADE, REPROCESSAR, SEQ,
        TIPCODBARRA, TIPGTINNFE, UNIDTRIB
    )
    (SELECT 
        CODBARRA, STP_GET_CODUSULOGADO, STP_GET_CODUSULOGADO, CODVOL,
        SYSDATE, SYSDATE, DIVIDEMULTIPLICA, V_NUNICO, QUANTIDADE, 'N',
        ROWNUM SEQ, TIPCODBARRA, TIPGTINNFE, UNIDTRIB 
     FROM TGFVOA 
     WHERE CODPROD = PARAM_CODPROD
    );

    P_MENSAGEM := 'Processo de importação realizado com sucesso!';
END;

/