CREATE OR REPLACE TRIGGER AD_TRG_INTEGRAPRODSAP
  for insert or update on AD_INTEGRAPRODSAP
  compound trigger
  
  /*----------------------------------------------------------------------------------------------------
  %proposito:   Adicionar os produtos integrados do SAP para o fluxo de produtos SKW
  %observacao: trigger faz parte do projeto de substituição do MITRA.   
  %historia: Criada para atendimento do briefing:
  https://docs.google.com/document/d/1o-U5oKX5WiKUQrP1IGEyA3LInDaipLJYVz4Vtunuji0/edit?tab=t.0
  * 01.00.0 02/01/2025 Diego.Alves
  - versao inicial
  ----------------------------------------------------------------------------------------------------*/
  V_NUNICO INT;
  V_USOPROD VARCHAR2(10);
  V_CODVOL VARCHAR2(10);
  V_CODGRUPOPROD INT;
  V_VAL_CODGRUPOPROD INT;
  V_VAL_CODVOL INT;
  V_CODPROD INT;

  BEFORE EACH ROW IS
  BEGIN 
    IF INSERTING THEN 
      :NEW.DHINCLUSAO := SYSDATE;
    END IF;

    IF UPDATING THEN 
      :NEW.DHATUALIZACAO := SYSDATE;

      SELECT COUNT(1)
      INTO V_VAL_CODVOL
      FROM TGFVOL
      WHERE AD_CODSAP = :NEW.CODVOL;

      IF V_VAL_CODVOL = 1 THEN
        SELECT NVL(CODVOL,'UN')
        INTO V_CODVOL
        FROM TGFVOL
        WHERE AD_CODSAP = :NEW.CODVOL;
      ELSE
        V_CODVOL := 'UN';
      END IF;

      SELECT COUNT(1)
      INTO V_VAL_CODGRUPOPROD
      FROM TGFGRU
      WHERE AD_CODSAP = :NEW.CODGRUPOPROD;

      IF V_VAL_CODGRUPOPROD = 1 THEN 
        SELECT NVL(CODGRUPOPROD,0)
        INTO V_CODGRUPOPROD
        FROM TGFGRU
        WHERE AD_CODSAP = :NEW.CODGRUPOPROD;
      ELSE 
        V_CODGRUPOPROD := 0;
      END IF;

      SELECT NUNICO
      INTO V_NUNICO
      FROM AD_TGFPROCAB 
      WHERE CODPROD = REGEXP_REPLACE(:NEW.CODPROD, '[^0-9]', '');

      UPDATE TGFPRO SET 
        AD_GRAMAMLPMPF = :NEW.AD_GRAMAMLPMPF, 
        AD_PALLET      = :NEW.AD_PALLET,
        ALTURA         = :NEW.ALTURA,
        CODGRUPOPROD   = V_CODGRUPOPROD,
        CODVOL         = V_CODVOL,
        DESCRPROD      = :NEW.DESCRPROD,
        ESPESSURA      = :NEW.ESPESSURA,
        LARGURA        = :NEW.LARGURA,
        M3             = :NEW.M3,
        NCM            = SUBSTR(:NEW.NCM, 1,8),
        CODEXNCM       = NVL(SUBSTR(:NEW.NCM, 12,1),0),
        ORIGPROD       = :NEW.ORIGPROD,
        PESOBRUTO      = :NEW.PESOBRUTO,
        PESOLIQ        = :NEW.PESOLIQ,
        QTDEMB         = :NEW.QTDEMB,
        REFERENCIA     = :NEW.REFERENCIA
      WHERE 
        CODPROD = REGEXP_REPLACE(:NEW.CODPROD, '[^0-9]', '');

      UPDATE AD_TGFPROCAB SET 
        CODGRUPOPROD = V_CODGRUPOPROD,
        CODVOL       = V_CODVOL,
        DESCRPROD    = :NEW.DESCRPROD,
        ORIGPROD     = :NEW.ORIGPROD,
        REFERENCIA   = :NEW.REFERENCIA
      WHERE NUNICO = V_NUNICO;

      UPDATE AD_TGFPROFIS SET 
        AD_GRAMAMLPMPF   = :NEW.AD_GRAMAMLPMPF,
        NCM              = SUBSTR(:NEW.NCM, 1,8),
        CODEXNCM         = NVL(SUBSTR(:NEW.NCM, 12,1),0)
      WHERE NUNICO = V_NUNICO;

      UPDATE AD_TGFPROGER SET 
        AD_PALLET   = :NEW.AD_PALLET,  
        ALTURA      = :NEW.ALTURA,
        ESPESSURA   = :NEW.ESPESSURA,
        LARGURA     = :NEW.LARGURA,
        M3          = :NEW.M3,
        PESOBRUTO   = :NEW.PESOBRUTO,
        PESOLIQ     = :NEW.PESOLIQ,
        QTDEMB      = :NEW.QTDEMB
      WHERE NUNICO = V_NUNICO;
    END IF;
  END BEFORE EACH ROW;

  AFTER EACH ROW IS 
  BEGIN 
    /*Valida a Inserção no fluxo 
        de parceiro de acordo com integração.*/
    IF INSERTING THEN
      /*Determina o USOPROD.*/
      V_USOPROD := 
        CASE 
          --WHEN :NEW.UTILIZACAOMATERIAL = '2' AND :NEW.TIPOMATERIAL = 'Qualquer' THEN 'C'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'ZEMB' THEN 'E'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'ROH'  THEN 'M'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'FERT' THEN 'V'
          WHEN :NEW.UTILIZACAOMATERIAL = '0' AND :NEW.TIPOMATERIAL = 'FERT' THEN 'V'
          WHEN :NEW.UTILIZACAOMATERIAL = '0' AND :NEW.TIPOMATERIAL = 'ZFME' THEN 'R'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'ZGRL' THEN 'P'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'HALB' THEN 'P'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'HAWA' THEN 'V'
          WHEN :NEW.UTILIZACAOMATERIAL = '0' AND :NEW.TIPOMATERIAL = 'HAWA' THEN 'V'
          WHEN :NEW.UTILIZACAOMATERIAL = '1' AND :NEW.TIPOMATERIAL = 'ZSOL' THEN 'M'
          WHEN :NEW.UTILIZACAOMATERIAL = '2' AND :NEW.TIPOMATERIAL = 'ZMEG' THEN 'E'
          WHEN :NEW.UTILIZACAOMATERIAL = '2' AND :NEW.TIPOMATERIAL = 'LEIH' THEN 'E'
          WHEN :NEW.UTILIZACAOMATERIAL = '2' AND :NEW.TIPOMATERIAL = 'ZDIP' THEN 'C'
          ELSE 'Z' -- Valor padrão caso nenhuma condição seja satisfeita
        END; 

      SELECT COUNT(1)
      INTO V_VAL_CODVOL
      FROM TGFVOL
      WHERE AD_CODSAP = :NEW.CODVOL;

      IF V_VAL_CODVOL = 1 THEN
        SELECT NVL(CODVOL,'UN')
        INTO V_CODVOL
        FROM TGFVOL
        WHERE AD_CODSAP = :NEW.CODVOL;
      ELSE
        V_CODVOL := 'UN';
      END IF;

      SELECT COUNT(1)
      INTO V_VAL_CODGRUPOPROD
      FROM TGFGRU
      WHERE AD_CODSAP = :NEW.CODGRUPOPROD;

      IF V_VAL_CODGRUPOPROD = 1 THEN 
        SELECT NVL(CODGRUPOPROD,0)
        INTO V_CODGRUPOPROD
        FROM TGFGRU
        WHERE AD_CODSAP = :NEW.CODGRUPOPROD;
      ELSE 
        V_CODGRUPOPROD := 0;
      END IF;

      SELECT MAX(NUNICO)+1
      INTO V_NUNICO
      FROM AD_TGFPROCAB;

      INSERT INTO AD_TGFPROCAB (
        NUNICO, CODPROD, DESCRPROD, USOPROD, DHINCLUSAO, CODUSUINCLUSAO, 
        USALOCAL, SOLCOMPRA, VENCOMPINDIV, USALOTEDTVAL, USALOTEDTFAB, TEMRASTROLOTE, 
        AD_IMPRIMEETIQUETA, AD_SEPARAPROD, CODGRUPOPROD, TIPLANCNOTA, TIPCONTEST, 
        ORIGPROD, CODLOCALPADRAO, CODVOL, FABRICANTE, AD_CODEND, REFERENCIA, 
        AD_DESCRICAOCOMEX, AD_OBSNF, AD_QTDMINVENDA, CARACTERISTICAS, PRODUTONFE, 
        CODUSU, APROVAFIS, AD_KITFANTASMA
      )
      VALUES (
        V_NUNICO, REGEXP_REPLACE(:NEW.CODPROD, '[^0-9]', ''), :NEW.DESCRPROD, V_USOPROD, 
        SYSDATE, 0, 'S', 'N', 'N', 'S', 'S', 'S', 'S', 'S', V_CODGRUPOPROD, 'Q', 'L', 
        :NEW.ORIGPROD, 0, V_CODVOL, NULL, NULL, SUBSTR(:NEW.REFERENCIA, 1, 15), NULL, 
        NULL, NULL, NULL, 1, 0, 0, NULL
      );

      INSERT INTO AD_TGFPROFIS (NUNICO, SEQ, AD_GRAMAMLPMPF, NCM, CODEXNCM) 
      VALUES(V_NUNICO, 1, :NEW.AD_GRAMAMLPMPF, SUBSTR(:NEW.NCM, 1,8), NVL(SUBSTR(:NEW.NCM, 12,1),0));

      INSERT INTO AD_TGFPROGER (NUNICO, SEQ, AD_PALLET, ALTURA, ESPESSURA, LARGURA, M3, PESOBRUTO, PESOLIQ, QTDEMB)
      VALUES (V_NUNICO, 1, :NEW.AD_PALLET, :NEW.ALTURA, :NEW.ESPESSURA, :NEW.LARGURA, :NEW.M3, :NEW.PESOBRUTO, :NEW.PESOLIQ, :NEW.QTDEMB);
    END IF;
  END AFTER EACH ROW;
END;

/